[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "2Uqhg4Ss6azaXnZnDUr1xHyzhQ1bbRuVdXEm1N8BAZ7W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/blackbox/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
